name: pyfoomb

channels:
  - defaults
  - conda-forge

dependencies:
  - python>=3.7
  - numpy
  - scipy
  - joblib
  - pandas>=0.24
  - openpyxl
  - matplotlib-base
  - seaborn-base
  - psutil
  - pip
  - assimulo
  - pygmo>=2.14